[package]
name = "probe-core"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-alloc  = { version = "0.6", optional = true, features = ["llff"] }
cortex-m-rt     = { version = "0.7", optional = true }
cortex-m        = { version = "0.7", optional = true, features = ["critical-section-single-core"] }
panic-halt      = { version = "1.0", optional = true }
critical-section = "1.1"

# --- serialization ---
serde   = { version = "1", default-features = false, features = ["derive"] }
bincode = { version = "2", features = ["serde"], optional = true } # Computer
postcard = { version = "1.1", features = ["alloc"], optional = true } # Firmware

[features]
computer = ["bincode"]
firmware = ["embedded-alloc", "cortex-m-rt", "panic-halt", "cortex-m", "postcard"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"