[package]
name = "sonde-core"
version = "0.1.0"
edition = "2024"

[dependencies]
static_cell = { version = "2.1", features = ["nightly"] }
esp-hal = { version = "1.0.0-rc.0", features = ["esp32s3", "unstable", "rt"] }
esp-println = { version = "0.16.1", features = ["esp32s3", "log-04"] }
esp-backtrace = { version = "0.18.1", features = ["esp32s3", "panic-handler", "colors", "println"] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32s3"] }
esp-alloc = { version = "0.9.0", default-features = false }
esp-rtos = { version = "0.2.0", features = ["esp32s3", "esp-radio", "esp-alloc", "embassy"] }
esp-radio = { version = "0.17.0", features = ["esp32s3", "ble", "unstable", "esp-alloc"] }
bt-hci = "0.6"
trouble-host = { version = "0.5.1", default-features = false, features = ["peripheral", "gatt", "default-packet-pool", "derive"] }

embassy-time = { version = "0.4.0", default-features = false }
embassy-sync = { version = "0.7.2", default-features = false }
embassy-executor = { version = "0.9.1", default-features = false }

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"

# OBLIGATOIRE : esp-radio ne peut pas connecter/advertiser sans opt-level 3
# Même en mode dev, ce package est compilé optimisé
[profile.dev.package.esp-radio]
opt-level = 3